version: '3.6'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: 'jenkins'
    user: 'root'
    ports:
      - 8080:8080
    volumes:
      - ./jenkins/plugins.txt:/usr/share/jenkins/ref/plugins.txt
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    command: >
        bash -c "jenkins-plugin-cli -f /usr/share/jenkins/ref/plugins.txt &&
                /usr/local/bin/jenkins.sh"
    networks: 
      - tp_network
networks:
  tp_network:
    name: tp_network
