apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: hizzo/my-image-python:latest  # Remplacez par l'image Docker de votre application Python
        ports:
        - containerPort: 80  # Port sur lequel votre application écoute
