apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: hizzo/my-image-python:latest  # Remplacez par l'image Docker de votre application Python
        ports:
        - containerPort: 5000  # Port sur lequel votre application écoute
---
apiVersion: v1
kind: Service
metadata:
  name: python-app
spec:
  type: LoadBalancer
  selector:
    app: python-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000