plugin: gcp_compute
zones: # populate inventory with instances in these regions
  - us-east1-b
projects:
  - pojet-ecole
service_account_file: ./service_account.json # à changer si vous avez modifié la variable file_name dans terraform
auth_kind: serviceaccount
keyed_groups:
  # Create groups from GCE labels
  - key: labels
    prefix: label
  - key: zone
    prefix: zone
hostnames:
  - name
compose:
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP
