- name: Configure docker
  hosts: instance-python-vm
  become: true
  tasks:
    - name: Install docker
      apt:
        name: 
          - docker.io
        state: present
    - name: installation de docker compose
      shell: sudo curl -L "https://github.com/docker/compose/releases/download/1.26.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    - name: Ajout des droits d'executions pour docker-compose
      shell: sudo chmod +x /usr/local/bin/docker-compose