- name: Configure docker
  hosts: instance-dev-vm
  become: true
  tasks:
    - name: Install docker
      apt:
        name: 
          - docker.io
        state: present
    - name: lance le docker run
      shell: docker run -d -p 80:5000 hizzo/my-image-python:latest || exit 0